### STAGE 1: Build ###
FROM node:18-alpine AS build

# If NODE_ENV is not passed as a build arg, go with production
ARG node_env_arg=production
EXPOSE 80

WORKDIR /usr/src/app
COPY . .
RUN npm ci
RUN npm run build -- --configuration ${node_env_arg}

### STAGE 2: Run ###
FROM nginx:1.24.0-alpine
COPY --from=build /usr/src/app/dist/angular /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

## forward request and error logs to standard output
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
	&& ln -sf /dev/stderr /var/log/nginx/error.log

CMD ["nginx", "-g", "daemon off;"]